// @ts-nocheck
import * as __fd_glob_161 from "../content/docs/reference/errors/unknown.mdx?collection=docs"
import * as __fd_glob_160 from "../content/docs/reference/errors/unable_to_link_account.mdx?collection=docs"
import * as __fd_glob_159 from "../content/docs/reference/errors/unable_to_get_user_info.mdx?collection=docs"
import * as __fd_glob_158 from "../content/docs/reference/errors/state_not_found.mdx?collection=docs"
import * as __fd_glob_157 from "../content/docs/reference/errors/state_mismatch.mdx?collection=docs"
import * as __fd_glob_156 from "../content/docs/reference/errors/signup_disabled.mdx?collection=docs"
import * as __fd_glob_155 from "../content/docs/reference/errors/oauth_provider_not_found.mdx?collection=docs"
import * as __fd_glob_154 from "../content/docs/reference/errors/no_code.mdx?collection=docs"
import * as __fd_glob_153 from "../content/docs/reference/errors/no_callback_url.mdx?collection=docs"
import * as __fd_glob_152 from "../content/docs/reference/errors/invalid_callback_request.mdx?collection=docs"
import * as __fd_glob_151 from "../content/docs/reference/errors/index.mdx?collection=docs"
import * as __fd_glob_150 from "../content/docs/reference/errors/email_not_found.mdx?collection=docs"
import * as __fd_glob_149 from "../content/docs/reference/errors/email_doesn't_match.mdx?collection=docs"
import * as __fd_glob_148 from "../content/docs/reference/errors/account_already_linked_to_different_user.mdx?collection=docs"
import * as __fd_glob_147 from "../content/docs/reference/telemetry.mdx?collection=docs"
import * as __fd_glob_146 from "../content/docs/reference/security.mdx?collection=docs"
import * as __fd_glob_145 from "../content/docs/reference/resources.mdx?collection=docs"
import * as __fd_glob_144 from "../content/docs/reference/options.mdx?collection=docs"
import * as __fd_glob_143 from "../content/docs/reference/faq.mdx?collection=docs"
import * as __fd_glob_142 from "../content/docs/reference/contributing.mdx?collection=docs"
import * as __fd_glob_141 from "../content/docs/plugins/username.mdx?collection=docs"
import * as __fd_glob_140 from "../content/docs/plugins/test-utils.mdx?collection=docs"
import * as __fd_glob_139 from "../content/docs/plugins/stripe.mdx?collection=docs"
import * as __fd_glob_138 from "../content/docs/plugins/sso.mdx?collection=docs"
import * as __fd_glob_137 from "../content/docs/plugins/siwe.mdx?collection=docs"
import * as __fd_glob_136 from "../content/docs/plugins/scim.mdx?collection=docs"
import * as __fd_glob_135 from "../content/docs/plugins/polar.mdx?collection=docs"
import * as __fd_glob_134 from "../content/docs/plugins/phone-number.mdx?collection=docs"
import * as __fd_glob_133 from "../content/docs/plugins/passkey.mdx?collection=docs"
import * as __fd_glob_132 from "../content/docs/plugins/organization.mdx?collection=docs"
import * as __fd_glob_131 from "../content/docs/plugins/open-api.mdx?collection=docs"
import * as __fd_glob_130 from "../content/docs/plugins/one-time-token.mdx?collection=docs"
import * as __fd_glob_129 from "../content/docs/plugins/one-tap.mdx?collection=docs"
import * as __fd_glob_128 from "../content/docs/plugins/oidc-provider.mdx?collection=docs"
import * as __fd_glob_127 from "../content/docs/plugins/oauth-proxy.mdx?collection=docs"
import * as __fd_glob_126 from "../content/docs/plugins/oauth-provider.mdx?collection=docs"
import * as __fd_glob_125 from "../content/docs/plugins/multi-session.mdx?collection=docs"
import * as __fd_glob_124 from "../content/docs/plugins/mcp.mdx?collection=docs"
import * as __fd_glob_123 from "../content/docs/plugins/magic-link.mdx?collection=docs"
import * as __fd_glob_122 from "../content/docs/plugins/last-login-method.mdx?collection=docs"
import * as __fd_glob_121 from "../content/docs/plugins/jwt.mdx?collection=docs"
import * as __fd_glob_120 from "../content/docs/plugins/i18n.mdx?collection=docs"
import * as __fd_glob_119 from "../content/docs/plugins/have-i-been-pwned.mdx?collection=docs"
import * as __fd_glob_118 from "../content/docs/plugins/generic-oauth.mdx?collection=docs"
import * as __fd_glob_117 from "../content/docs/plugins/email-otp.mdx?collection=docs"
import * as __fd_glob_116 from "../content/docs/plugins/dub.mdx?collection=docs"
import * as __fd_glob_115 from "../content/docs/plugins/dodopayments.mdx?collection=docs"
import * as __fd_glob_114 from "../content/docs/plugins/device-authorization.mdx?collection=docs"
import * as __fd_glob_113 from "../content/docs/plugins/creem.mdx?collection=docs"
import * as __fd_glob_112 from "../content/docs/plugins/community-plugins.mdx?collection=docs"
import * as __fd_glob_111 from "../content/docs/plugins/commet.mdx?collection=docs"
import * as __fd_glob_110 from "../content/docs/plugins/captcha.mdx?collection=docs"
import * as __fd_glob_109 from "../content/docs/plugins/bearer.mdx?collection=docs"
import * as __fd_glob_108 from "../content/docs/plugins/autumn.mdx?collection=docs"
import * as __fd_glob_107 from "../content/docs/plugins/api-key.mdx?collection=docs"
import * as __fd_glob_106 from "../content/docs/plugins/anonymous.mdx?collection=docs"
import * as __fd_glob_105 from "../content/docs/plugins/admin.mdx?collection=docs"
import * as __fd_glob_104 from "../content/docs/plugins/2fa.mdx?collection=docs"
import * as __fd_glob_103 from "../content/docs/integrations/waku.mdx?collection=docs"
import * as __fd_glob_102 from "../content/docs/integrations/tanstack.mdx?collection=docs"
import * as __fd_glob_101 from "../content/docs/integrations/svelte-kit.mdx?collection=docs"
import * as __fd_glob_100 from "../content/docs/integrations/solid-start.mdx?collection=docs"
import * as __fd_glob_99 from "../content/docs/integrations/react-router.mdx?collection=docs"
import * as __fd_glob_98 from "../content/docs/integrations/nuxt.mdx?collection=docs"
import * as __fd_glob_97 from "../content/docs/integrations/nitro.mdx?collection=docs"
import * as __fd_glob_96 from "../content/docs/integrations/next.mdx?collection=docs"
import * as __fd_glob_95 from "../content/docs/integrations/nestjs.mdx?collection=docs"
import * as __fd_glob_94 from "../content/docs/integrations/lynx.mdx?collection=docs"
import * as __fd_glob_93 from "../content/docs/integrations/hono.mdx?collection=docs"
import * as __fd_glob_92 from "../content/docs/integrations/fastify.mdx?collection=docs"
import * as __fd_glob_91 from "../content/docs/integrations/express.mdx?collection=docs"
import * as __fd_glob_90 from "../content/docs/integrations/expo.mdx?collection=docs"
import * as __fd_glob_89 from "../content/docs/integrations/elysia.mdx?collection=docs"
import * as __fd_glob_88 from "../content/docs/integrations/electron.mdx?collection=docs"
import * as __fd_glob_87 from "../content/docs/integrations/convex.mdx?collection=docs"
import * as __fd_glob_86 from "../content/docs/integrations/astro.mdx?collection=docs"
import * as __fd_glob_85 from "../content/docs/guides/your-first-plugin.mdx?collection=docs"
import * as __fd_glob_84 from "../content/docs/guides/workos-migration-guide.mdx?collection=docs"
import * as __fd_glob_83 from "../content/docs/guides/supabase-migration-guide.mdx?collection=docs"
import * as __fd_glob_82 from "../content/docs/guides/saml-sso-with-okta.mdx?collection=docs"
import * as __fd_glob_81 from "../content/docs/guides/optimizing-for-performance.mdx?collection=docs"
import * as __fd_glob_80 from "../content/docs/guides/next-auth-migration-guide.mdx?collection=docs"
import * as __fd_glob_79 from "../content/docs/guides/create-a-db-adapter.mdx?collection=docs"
import * as __fd_glob_78 from "../content/docs/guides/clerk-migration-guide.mdx?collection=docs"
import * as __fd_glob_77 from "../content/docs/guides/browser-extension-guide.mdx?collection=docs"
import * as __fd_glob_76 from "../content/docs/guides/auth0-migration-guide.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/examples/svelte-kit.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/examples/react-router.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/examples/nuxt.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/examples/next-js.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/examples/astro.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/concepts/users-accounts.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/concepts/typescript.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/concepts/session-management.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/concepts/rate-limit.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/concepts/plugins.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/concepts/oauth.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/concepts/hooks.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/concepts/email.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/concepts/dynamic-base-url.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/concepts/database.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/concepts/cookies.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/concepts/client.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/concepts/cli.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/concepts/api.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/authentication/zoom.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/authentication/vk.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/authentication/vercel.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/authentication/twitter.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/authentication/twitch.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/authentication/tiktok.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/authentication/spotify.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/authentication/slack.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/authentication/salesforce.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/authentication/roblox.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/authentication/reddit.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/authentication/railway.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/authentication/polar.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/authentication/paypal.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/authentication/paybin.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/authentication/other-social-providers.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/authentication/notion.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/authentication/naver.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/authentication/microsoft.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/authentication/linkedin.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/authentication/linear.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/authentication/line.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/authentication/kick.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/authentication/kakao.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/authentication/huggingface.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/authentication/google.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/authentication/gitlab.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/authentication/github.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/authentication/figma.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/authentication/facebook.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/authentication/email-password.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/authentication/dropbox.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/authentication/discord.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/authentication/cognito.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/authentication/atlassian.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/authentication/apple.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/adapters/sqlite.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/adapters/prisma.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/adapters/postgresql.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/adapters/other-relational-databases.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/adapters/mysql.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/adapters/mssql.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/adapters/mongo.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/adapters/drizzle.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/adapters/community-adapters.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/introduction.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/installation.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/comparison.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/basic-usage.mdx?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_6 from "../content/changelogs/1.0.mdx?collection=changelogCollection"
import * as __fd_glob_5 from "../content/changelogs/1-2.mdx?collection=changelogCollection"
import * as __fd_glob_4 from "../content/blogs/seed-round.mdx?collection=blogCollection"
import * as __fd_glob_3 from "../content/blogs/authjs-joins-better-auth.mdx?collection=blogCollection"
import * as __fd_glob_2 from "../content/blogs/1-4.mdx?collection=blogCollection"
import * as __fd_glob_1 from "../content/blogs/1-3.mdx?collection=blogCollection"
import * as __fd_glob_0 from "../content/blogs/0-supabase-auth-to-planetscale-migration.mdx?collection=blogCollection"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
} & {
  DocData: {
    blogCollection: {
      /**
       * Last modified date of document file, obtained from version control.
       *
       */
      lastModified?: Date;
    },
    changelogCollection: {
      /**
       * Last modified date of document file, obtained from version control.
       *
       */
      lastModified?: Date;
    },
    docs: {
      /**
       * Last modified date of document file, obtained from version control.
       *
       */
      lastModified?: Date;
    },
  }
}>({"doc":{"passthroughs":["extractedReferences","lastModified"]}});

export const blogCollection = await create.doc("blogCollection", "content/blogs", {"0-supabase-auth-to-planetscale-migration.mdx": __fd_glob_0, "1-3.mdx": __fd_glob_1, "1-4.mdx": __fd_glob_2, "authjs-joins-better-auth.mdx": __fd_glob_3, "seed-round.mdx": __fd_glob_4, });

export const changelogCollection = await create.doc("changelogCollection", "content/changelogs", {"1-2.mdx": __fd_glob_5, "1.0.mdx": __fd_glob_6, });

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_7, }, {"basic-usage.mdx": __fd_glob_8, "comparison.mdx": __fd_glob_9, "installation.mdx": __fd_glob_10, "introduction.mdx": __fd_glob_11, "adapters/community-adapters.mdx": __fd_glob_12, "adapters/drizzle.mdx": __fd_glob_13, "adapters/mongo.mdx": __fd_glob_14, "adapters/mssql.mdx": __fd_glob_15, "adapters/mysql.mdx": __fd_glob_16, "adapters/other-relational-databases.mdx": __fd_glob_17, "adapters/postgresql.mdx": __fd_glob_18, "adapters/prisma.mdx": __fd_glob_19, "adapters/sqlite.mdx": __fd_glob_20, "authentication/apple.mdx": __fd_glob_21, "authentication/atlassian.mdx": __fd_glob_22, "authentication/cognito.mdx": __fd_glob_23, "authentication/discord.mdx": __fd_glob_24, "authentication/dropbox.mdx": __fd_glob_25, "authentication/email-password.mdx": __fd_glob_26, "authentication/facebook.mdx": __fd_glob_27, "authentication/figma.mdx": __fd_glob_28, "authentication/github.mdx": __fd_glob_29, "authentication/gitlab.mdx": __fd_glob_30, "authentication/google.mdx": __fd_glob_31, "authentication/huggingface.mdx": __fd_glob_32, "authentication/kakao.mdx": __fd_glob_33, "authentication/kick.mdx": __fd_glob_34, "authentication/line.mdx": __fd_glob_35, "authentication/linear.mdx": __fd_glob_36, "authentication/linkedin.mdx": __fd_glob_37, "authentication/microsoft.mdx": __fd_glob_38, "authentication/naver.mdx": __fd_glob_39, "authentication/notion.mdx": __fd_glob_40, "authentication/other-social-providers.mdx": __fd_glob_41, "authentication/paybin.mdx": __fd_glob_42, "authentication/paypal.mdx": __fd_glob_43, "authentication/polar.mdx": __fd_glob_44, "authentication/railway.mdx": __fd_glob_45, "authentication/reddit.mdx": __fd_glob_46, "authentication/roblox.mdx": __fd_glob_47, "authentication/salesforce.mdx": __fd_glob_48, "authentication/slack.mdx": __fd_glob_49, "authentication/spotify.mdx": __fd_glob_50, "authentication/tiktok.mdx": __fd_glob_51, "authentication/twitch.mdx": __fd_glob_52, "authentication/twitter.mdx": __fd_glob_53, "authentication/vercel.mdx": __fd_glob_54, "authentication/vk.mdx": __fd_glob_55, "authentication/zoom.mdx": __fd_glob_56, "concepts/api.mdx": __fd_glob_57, "concepts/cli.mdx": __fd_glob_58, "concepts/client.mdx": __fd_glob_59, "concepts/cookies.mdx": __fd_glob_60, "concepts/database.mdx": __fd_glob_61, "concepts/dynamic-base-url.mdx": __fd_glob_62, "concepts/email.mdx": __fd_glob_63, "concepts/hooks.mdx": __fd_glob_64, "concepts/oauth.mdx": __fd_glob_65, "concepts/plugins.mdx": __fd_glob_66, "concepts/rate-limit.mdx": __fd_glob_67, "concepts/session-management.mdx": __fd_glob_68, "concepts/typescript.mdx": __fd_glob_69, "concepts/users-accounts.mdx": __fd_glob_70, "examples/astro.mdx": __fd_glob_71, "examples/next-js.mdx": __fd_glob_72, "examples/nuxt.mdx": __fd_glob_73, "examples/react-router.mdx": __fd_glob_74, "examples/svelte-kit.mdx": __fd_glob_75, "guides/auth0-migration-guide.mdx": __fd_glob_76, "guides/browser-extension-guide.mdx": __fd_glob_77, "guides/clerk-migration-guide.mdx": __fd_glob_78, "guides/create-a-db-adapter.mdx": __fd_glob_79, "guides/next-auth-migration-guide.mdx": __fd_glob_80, "guides/optimizing-for-performance.mdx": __fd_glob_81, "guides/saml-sso-with-okta.mdx": __fd_glob_82, "guides/supabase-migration-guide.mdx": __fd_glob_83, "guides/workos-migration-guide.mdx": __fd_glob_84, "guides/your-first-plugin.mdx": __fd_glob_85, "integrations/astro.mdx": __fd_glob_86, "integrations/convex.mdx": __fd_glob_87, "integrations/electron.mdx": __fd_glob_88, "integrations/elysia.mdx": __fd_glob_89, "integrations/expo.mdx": __fd_glob_90, "integrations/express.mdx": __fd_glob_91, "integrations/fastify.mdx": __fd_glob_92, "integrations/hono.mdx": __fd_glob_93, "integrations/lynx.mdx": __fd_glob_94, "integrations/nestjs.mdx": __fd_glob_95, "integrations/next.mdx": __fd_glob_96, "integrations/nitro.mdx": __fd_glob_97, "integrations/nuxt.mdx": __fd_glob_98, "integrations/react-router.mdx": __fd_glob_99, "integrations/solid-start.mdx": __fd_glob_100, "integrations/svelte-kit.mdx": __fd_glob_101, "integrations/tanstack.mdx": __fd_glob_102, "integrations/waku.mdx": __fd_glob_103, "plugins/2fa.mdx": __fd_glob_104, "plugins/admin.mdx": __fd_glob_105, "plugins/anonymous.mdx": __fd_glob_106, "plugins/api-key.mdx": __fd_glob_107, "plugins/autumn.mdx": __fd_glob_108, "plugins/bearer.mdx": __fd_glob_109, "plugins/captcha.mdx": __fd_glob_110, "plugins/commet.mdx": __fd_glob_111, "plugins/community-plugins.mdx": __fd_glob_112, "plugins/creem.mdx": __fd_glob_113, "plugins/device-authorization.mdx": __fd_glob_114, "plugins/dodopayments.mdx": __fd_glob_115, "plugins/dub.mdx": __fd_glob_116, "plugins/email-otp.mdx": __fd_glob_117, "plugins/generic-oauth.mdx": __fd_glob_118, "plugins/have-i-been-pwned.mdx": __fd_glob_119, "plugins/i18n.mdx": __fd_glob_120, "plugins/jwt.mdx": __fd_glob_121, "plugins/last-login-method.mdx": __fd_glob_122, "plugins/magic-link.mdx": __fd_glob_123, "plugins/mcp.mdx": __fd_glob_124, "plugins/multi-session.mdx": __fd_glob_125, "plugins/oauth-provider.mdx": __fd_glob_126, "plugins/oauth-proxy.mdx": __fd_glob_127, "plugins/oidc-provider.mdx": __fd_glob_128, "plugins/one-tap.mdx": __fd_glob_129, "plugins/one-time-token.mdx": __fd_glob_130, "plugins/open-api.mdx": __fd_glob_131, "plugins/organization.mdx": __fd_glob_132, "plugins/passkey.mdx": __fd_glob_133, "plugins/phone-number.mdx": __fd_glob_134, "plugins/polar.mdx": __fd_glob_135, "plugins/scim.mdx": __fd_glob_136, "plugins/siwe.mdx": __fd_glob_137, "plugins/sso.mdx": __fd_glob_138, "plugins/stripe.mdx": __fd_glob_139, "plugins/test-utils.mdx": __fd_glob_140, "plugins/username.mdx": __fd_glob_141, "reference/contributing.mdx": __fd_glob_142, "reference/faq.mdx": __fd_glob_143, "reference/options.mdx": __fd_glob_144, "reference/resources.mdx": __fd_glob_145, "reference/security.mdx": __fd_glob_146, "reference/telemetry.mdx": __fd_glob_147, "reference/errors/account_already_linked_to_different_user.mdx": __fd_glob_148, "reference/errors/email_doesn't_match.mdx": __fd_glob_149, "reference/errors/email_not_found.mdx": __fd_glob_150, "reference/errors/index.mdx": __fd_glob_151, "reference/errors/invalid_callback_request.mdx": __fd_glob_152, "reference/errors/no_callback_url.mdx": __fd_glob_153, "reference/errors/no_code.mdx": __fd_glob_154, "reference/errors/oauth_provider_not_found.mdx": __fd_glob_155, "reference/errors/signup_disabled.mdx": __fd_glob_156, "reference/errors/state_mismatch.mdx": __fd_glob_157, "reference/errors/state_not_found.mdx": __fd_glob_158, "reference/errors/unable_to_get_user_info.mdx": __fd_glob_159, "reference/errors/unable_to_link_account.mdx": __fd_glob_160, "reference/errors/unknown.mdx": __fd_glob_161, });